add hw1
SiERic/JavaHW pull request #1
Opened 2019-01-26 21:32 UTC by SiERic

2019-01-28 18:21 UTC, jzuken requested changes

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/HashTable.java
> +package me.sieric.hashtable;
ну, наверное, не стоит это всё складировать прямо в корень репозитория. как это всё потом с другими задачами будет мерджиться?

2019-01-28 18:21 UTC, jzuken commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-bin.zip
а конфиги гредла где? в будущем буду за такое баллы снимать

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/HashTable.java
> +    private static final int HASH_BASE = 239, INITIAL_CAPACITY = 2;
лучше не объявлять несколько полей/констант в одной строчке

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/HashTable.java
> +    /**
однострочные доки лучше так и писать в одну строку: `/** ... */`

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/HashTable.java
> +    public String put(String key, String value) {
а если аргументы некорректны, лучше бросать исключение

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/List.java
> +    public class Node {
а если сделать списку итератор, то этот класс (то есть детали реализации списка) не надо будет раскрывать наружу

2019-01-28 18:21 UTC, jzuken commented on src/main/java/me/sieric/hashtable/List.java
> +        head = tail = null;
опять же, лучше не писать больше одного оператора на строке. читаемость кода от этого не повышается

2019-01-29 19:07 UTC, SiERic commented
Хорошо, это всё имело смысл

2019-02-13 12:33 UTC, jzuken requested changes

2019-02-13 12:33 UTC, jzuken commented on hw1-hashtable/src/main/java/me/sieric/hashtable/HashTable.java
> +        data = new List[capacity];
инициализацию лучше делать при объявлении

2019-02-13 12:33 UTC, jzuken commented on hw1-hashtable/src/main/java/me/sieric/hashtable/List.java
> +    public List() {
этот конструктор тоже довольно бессмысленный

2019-02-13 12:33 UTC, jzuken commented on hw1-hashtable/src/main/java/me/sieric/hashtable/List.java
> +    private class Node {
вложенные классы, особенно приватные, лучше уносить в конец класса

2019-02-13 12:33 UTC, jzuken commented on hw1-hashtable/src/main/java/me/sieric/hashtable/List.java
> +        private Node cur;
не надо такие сокращения делать, буду за это баллы снимать

2019-02-13 12:33 UTC, jzuken commented on hw1-hashtable/src/test/java/me/sieric/hashtable/HashTableTest.java
> +
лишних пустых строчек не надо

2019-03-07 10:57 UTC, jzuken commented
конфликт с мастером

2019-03-07 11:02 UTC, jzuken commented on hw1-hashtable/src/main/java/me/sieric/hashtable/HashTable.java
> +     * @throws IllegalArgumentException if string is null
ну, по-хорошему тут надо бы написать, что именно вы не хотите, чтобы было null

2019-03-10 16:42 UTC, merged