hw8
SiERic/JavaHW pull request #12
Opened 2019-05-20 20:42 UTC by SiERic

2019-05-31 11:21 UTC, RamSaw requested changes
@SiERic проверил. Небольшие комменты есть, +1 за тесты, пока только у Вас их видел.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/build.gradle
> +mainClassName = 'me.sieric.cannon.Main'
jar не запускается

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Bullet.java
> +    private static final double G = 9.81;
вы первая кто использует нормальное g :) респект

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/settings.gradle
> +rootProject.name = 'cannon'
круто, что игра с уровнями. Добавьте только еще текста о том, как менять размер снаряда

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Bullet.java
> +    private final double speed;
так может хранить это в типе BulletType, который будет enum?

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Bullet.java
> +        types.add(new BulletType(minRadius + 4, minSpeed));
мне кажется enum понятней и красивей выглядит, или вы хотите сделать поддержку кучи типов снарядов?

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Bullet.java
> +        return (int) (y0 - speed * time * Math.sin(angle) / TIME_CONST + G * time * time / 2 / TIME_CONST / TIME_CONST);
а почему не сделать их double? JavaFX спокойно с double работает

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Bullet.java
> +        return types.get(type).radius * types.get(type).radius / 4;
это все же к типу относиться, а не к самой пуле. То есть этот метод спокойно в enum можно кинуть.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Cannon.java
> +    /** Y coordinate of body center (and the beginning of tje barrel) */
the*

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Cannon.java
> +        barrel.setEndX(x + BARREL_LENGTH * Math.cos(angle));
getBarrelEndX?

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Landscape.java
> +    private ArrayList<Point> points = new ArrayList<>();
мне кажется это мб источником бага. Вам надо будет поддерживать инвариант, что точки в этом листе, это такие же как в mounts. Мб просто использовать всегда список lines?

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Landscape.java
> +    private static class Point {
в JavaFX есть Point2D, там и в придачу куча удобных методов для работы с векторами.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Main.java
> + *   ENTER to fire
я думаю игроки игры не будут читать джавадок :). Надо это выводить юзеру, в джавадоке наверное это совсем ненужно.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Main.java
> +        Thread timerThread = new Thread(() -> {
вообще я думаю можно было бы обойтись средствами JavaFX только. К примеру там есть AnimationTimer, которым пользовались почти все ваши сокурсники. Но так тоже норм.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/settings.gradle
> +rootProject.name = 'cannon'
`(java:25927): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`

Еще это вылетает. Вероятно это из-за того, что что-то пошло не так в JavaFX. Почитайте интернет, мб это можно как-то пофиксить.

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Main.java
> +
пустая строка

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Main.java
> +        return (Math.hypot(cannon.getBody().getCenterX() - target.getCenterX(),
а зачем внешние скобки?

2019-05-31 11:21 UTC, RamSaw commented on hw8-cannon/src/main/java/me/sieric/cannon/Main.java
> +                    && newY - bullet.getRadius() / 2 <= landscape.getYByX(newX)
а почему вы делите на 2? это диаметр в итоге, а не радиус?

2019-06-06 22:27 UTC, SiERic commented on hw8-cannon/settings.gradle
> +rootProject.name = 'cannon'
Я примерно знаю, что ему не нравится, но мне не хочется всё переписывать, чтобы оно починилось

2019-06-06 22:27 UTC, SiERic commented
А всё остальное я, вроде, исправила
@RamSaw

2019-06-07 17:16 UTC, RamSaw commented on hw8-cannon/settings.gradle
> +rootProject.name = 'cannon'
А что ему не нравится?

2019-06-07 17:25 UTC, RamSaw approved these changes
@SiERic все ок
@jzuken

2019-06-08 08:14 UTC, merged