hw3
SiERic/JavaHW pull request #4
Opened 2019-02-11 19:54 UTC by SiERic

2019-02-25 18:09 UTC, RamSaw requested changes
@SiERic домашку проверил, жду исправлений или контраргументов.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/build.gradle
> +    testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.0.1'
а Вы и 4 и 5 пользуетесь?

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        tree = new Tree<>((a, other) -> ((Comparable) a).compareTo(other));
Raw types это плохо, кастуйте к Comparable<? super E>

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        MyTreeSet<E> newts = new MyTreeSet<>();
плохо понятное сокращение

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        if (isAscending) {
тернарный оператор

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        if (isAscending) {
и всех других случаев тоже касается

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    @Nullable
first и last они не nullable.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    public boolean add(E e) {
Nullable? Вообще null поддерживается

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    public boolean add(E e) {
Для contains и remove тоже

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +
Зачем пустая строчка? Давайте уберем static и дженерик тип.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private Node lowerBound(@NotNull E key) {
Согласно TreeSet из стандартной библеотеки может быть Nullable.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private Node lowerBound(@NotNull E key) {
Остальных методов тоже касается

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                int cmpResult = comparator.compare(node.key, (E) o);
Это плохой каст, потому что Object не обязательно должен быть типом E. Он может просто учавствовать в дереве наследования типа E.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +            Node node = lowerBound((E) o);
добавьте Object.requireNonNull, покажет, что вы ожидаете, что не будет null.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private void clear() {
version надо увеличивать, данные изменились же.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    MyTreeSet<Integer> tree;
private

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        MyTreeSet<String> emptyTree = new MyTreeSet<>();
var?

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    void testRemove() {
напишите тесты, когда Вы в remove и contains передадите НЕ тип E и НЕ его наследника, но при этом не выкинется ClassCastException. В Вашей реализации он всегда выкинется, но есть случаи когда не должен.

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    void testLast() {
Тесты на поведение при пустом дереве добавить бы

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        MyTreeSet<Integer> cmpTree = new MyTreeSet(Comparator.comparingInt(a -> (int) a % 10));
var и Вы забыли <> после new у типа

2019-02-25 18:09 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private void clear() {
И соответственно тестов на это надо добавить

2019-03-04 15:17 UTC, SiERic commented on hw3-treeset/build.gradle
> +    testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.0.1'
Хм, и правда

2019-03-04 15:17 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        tree = new Tree<>((a, other) -> ((Comparable) a).compareTo(other));
Тоже справедливо

2019-03-04 15:17 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        MyTreeSet<E> newts = new MyTreeSet<>();
Ладно, теперь более понятное

2019-03-04 15:18 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        if (isAscending) {
Действительно

2019-03-04 15:18 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    @Nullable
Что, почему? А если дерево пустое?

2019-03-04 15:25 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private void clear() {
Ок

2019-03-04 15:25 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    MyTreeSet<Integer> tree;
да, и правда

2019-03-04 15:30 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        MyTreeSet<String> emptyTree = new MyTreeSet<>();
ну да

2019-03-04 15:33 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +
ok

2019-03-04 15:38 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        MyTreeSet<Integer> cmpTree = new MyTreeSet(Comparator.comparingInt(a -> (int) a % 10));
справедливо

2019-03-04 16:01 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private Node lowerBound(@NotNull E key) {
ok

2019-03-04 16:11 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    public boolean add(E e) {
ок

2019-03-04 16:20 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    void testLast() {
ok

2019-03-04 16:40 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                int cmpResult = comparator.compare(node.key, (E) o);
что-то не очевидно, как это делать
и кажется, что в жизни такое не сильно нужно

2019-03-05 20:48 UTC, RamSaw requested changes
@SiERic проверил, жду исправлений. Если есть вопросы пишите. Позовите меня @RamSaw когда исправите.
Тимофей попросил сразу говорить, за что баллы сняты:
-1 за не поддерживаемость других типов в contains, -1 за мелкий стайлгайд: тернарный оператор, сокращение имен переменных и var.
+2 за инвалидацию добавил.

2019-03-05 20:48 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    @Nullable
Дело в том, что дерево может содержать null. Надо кидать исключение. Посмотрите документацию стандартного TreeSet.

2019-03-05 20:48 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                int cmpResult = comparator.compare(node.key, (E) o);
Ну, порой может пригодится. Берешь объект и просто обучаешь его сравниваться с типом E. А потом по нему удаляешь или проверяешь наличие. Ну а в домашке интересно сделать, чтобы прочувствовать дженерики. А сделать это можно, разделив случаи, когда передан comparator и когда не передан.

2019-03-05 20:48 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                return false;
так не содержим null в итоге?

2019-03-05 20:48 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                return false;
Судя по коду ниже нет. Почитайте документацию стандартного TreeSet. Там четко описано как хранятся null.

2019-03-12 11:25 UTC, SiERic commented
@RamSaw Ок, я, кажется, научила его хранить null и сравниваться со странными классами

2019-03-15 14:36 UTC, RamSaw requested changes
@SiERic исправления проверил. Там вроде замечания только косметические всякие остались, так что исправляйте и будем пытаться смержить :)

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +            Node(E key, @Nullable Node parent) {
Nullable

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +            Node(E key, @Nullable Node parent) {
Вы во многих местах убрали NotNull, так давайте добавим Nullable тогда во все эти места.

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                compare(e, e);
второй раз уже вижу такой вызов и всегда трудно понять, что же он делает. Насколько помню, это чтобы проверить поддерживаются ли null. Так давайте выделим отдельный метод и назовем его так, чтобы было понятно. Или же заифайте напрямую как нибудь. А лучше заифайте и выделите в отедльную функцию. Так наиболее понятный код получится, на мой взгляд.

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                compare(e, e);
Да и странно, почему Вы делаете это только в этом ифе, а в других нет. Наверное, это ошибка. Или нет?

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        private int compare(Object o1, Object o2) {
Сделайте уж o2 типа E. Все равно же все время кастуете к нему, да и в коде всегда можно вторым аргументом передавать тип E.

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        // tree = {1, 4, 6, 10, 15, 16, 19, 21, 24}
что это? просто если Вы написали какие там будут элементы, может просто сразу проинициализировать этими числами? Вряд ли Вы захотите создать больше чисел для теста.

2019-03-15 14:36 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +    private static class Kek implements Comparable<Kek> {
такие себе названия конечно. Я, кстати, раньше тоже так писал и Тимофей вроде не ругался, но, блин, тут же есть явный смысл, кто чей наследник и кто какую роль играет. Давайте в соответствии с этим и назовем классы.

2019-03-17 23:48 UTC, SiERic commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +                compare(e, e);
Там если дерево не пустое, вызывается lowerBound, который внутри этот compare вызывает

2019-03-17 23:50 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        // tree = {1, 4, 6, 10, 15, 16, 19, 21, 24}
Мне нужно было, чтобы элементы добавлялись неупорядоченно, поэтому там (15 i * i) % 30, а комментарий, чтобы знать, что там лежит

2019-03-17 23:51 UTC, SiERic commented
@RamSaw, я что-то исправила (а что-то нет)

2019-03-19 21:42 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        // tree = {1, 4, 6, 10, 15, 16, 19, 21, 24}
ладно, ок. Но выглядит как отдельный юнит тест под названием "UnorderedFillingTree".

2019-03-19 21:50 UTC, RamSaw requested changes
@SiERic посмотрел. К сожалению, появились новые замечания :(
конфликт с мастером, кстати, пофиксите, а то смержить не будет возможно.

2019-03-19 21:50 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +        void checkNull() {
private?
-0.5

2019-03-19 21:50 UTC, RamSaw commented on hw3-treeset/src/main/java/me/sieric/treeset/MyTreeSet.java
> +    @Override @NotNull
нет, по-моему было правильно и он Nullable. Дерево же может хранить null.
Ниже тоже самое.

2019-03-19 21:50 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        MyTreeSet<Base> kekTree = new MyTreeSet<>();
baseTree?

2019-03-19 21:50 UTC, RamSaw commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        public int compareTo(@NotNull MyTreeSetTest.Base o) {
а тут разве нельзя просто Base, без "MyTreeSetTest."?

2019-03-20 00:43 UTC, SiERic commented on hw3-treeset/src/test/java/me/sieric/treeset/MyTreeSetTest.java
> +        public int compareTo(@NotNull MyTreeSetTest.Base o) {
Можно, просто idea там сама сигнатуры методов написала

2019-03-20 00:45 UTC, SiERic commented
@RamSaw 
Ну теперь-то, надеюсь, всё норм

2019-03-20 20:13 UTC, RamSaw approved these changes
@SiERic ok.
@jzuken

2019-03-21 19:24 UTC, merged